### ISSUE TITLE
File format not supported: danfojs-node

### ISSUE THREAD

**Issue by bernarma** [opensource9ja/danfojs#277]
**Describe the bug**
Attempting to drop na's from a Series where first value is null and a "File format not supported message" returned.

**To Reproduce**
Run the following code:

new dfd.Series([null, 100, null, 200], { index: [0, 1, 2, 3] })
            .dropna()
            .print();

Node JS: v12.22.1

**Expected behavior**
Standard Print() without the 2 null entries.

**Additional context**
Error: File format not supported
    at new NDframe (/Users/berniemac/Develop/projekt1/server/node_modules/danfojs-node/dist/core/generic.js:43:15)
    at new Series (/Users/berniemac/Develop/projekt1/server/node_modules/danfojs-node/dist/core/series.js:39:7)
    at /Users/berniemac/Develop/projekt1/server/src/expression/lib/math/function/statistics/max.js:62:11
    at Array.forEach (<anonymous>)
    at Function._maxHandler (/Users/berniemac/Develop/projekt1/server/src/expression/lib/math/function/statistics/max.js:59:21)
    at /Users/berniemac/Develop/projekt1/server/node_modules/typed-function/typed-function.js:1108:43
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by risenW** [comment]
Fixed in latest version v0.3.0
